ManarAlSabeel.Web/Controllers/ExamController.cs
using ManarAlSabeel.Domain.Abstract;
using ManarAlSabeel.Domain.Entities;
using ManarAlSabeel.Resources;
using ManarAlSabeel.Web.Infrastructure;
using ManarAlSabeel.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManarAlSabeel.Web.Controllers
{
	[ForbiddenRedirectAuthorizeAttribute]
    public class ExamController : Controller
    {
		private ICenterRepository dbRepository;
		public ExamController(ICenterRepository repo)
		{
			dbRepository = repo;
		}

		public ViewResult List(int? registeredStudentId, int? examType, int? semesterId)
		{
			IQueryable<Exam> exams = new List<Exam>().AsQueryable();
			if (registeredStudentId.HasValue)
			{
				exams = dbRepository.GetAllExams().Where(exam => exam.RegisteredStudent.ID == registeredStudentId.Value).OrderBy(exam => exam.Date);
			}

			if (examType.HasValue && semesterId.HasValue)
			{
				exams = dbRepository.GetAllExams().Where(exam => exam.Type.ID == examType.Value
					&& exam.RegisteredStudent.Class.Semester.ID == semesterId.Value).OrderBy(exam => exam.Date);
			}

			return View(new ExamsListViewModel { Exams = exams });
		}

		public ViewResult Create(int registeredStudentId)
		{
			ExamEditViewModel examEditViewModel = new ExamEditViewModel();
			examEditViewModel.Date = DateTime.Now;
			examEditViewModel.RegistredStudentID = registeredStudentId;

			examEditViewModel.Teachers = dbRepository.GetAllTeachers();
			examEditViewModel.ExternalSupervisors = dbRepository.GetAllExternalSupervisors();
			examEditViewModel.ExamTypes = dbRepository.GetAllExamTypes();
			examEditViewModel.ExamGrades = dbRepository.GetAllExamGrades();

			return View("Edit", examEditViewModel);
		}

		public ViewResult Edit(int id)
		{
			ExamEditViewModel examEditViewModel = null;
			Exam examEntity = dbRepository.GetAllExams().FirstOrDefault<Exam>(x => x.ID == id);
			if (examEntity != null)
			{
				examEditViewModel = new ExamEditViewModel();
				examEditViewModel.ID = examEntity.ID;
				examEditViewModel.RegistredStudentID = examEntity.RegisteredStudent.ID;
				examEditViewModel.SupervisorID = examEntity.Supervisor.ID;
				examEditViewModel.ExternalSupervisorID = (examEntity.ExternalSupervisor != null) ? examEntity.ExternalSupervisor.ID : 0;
				examEditViewModel.Date = examEntity.Date;
				examEditViewModel.Comments = examEntity.Comments;
				examEditViewModel.BonusPoints = examEntity.BonusPoints;

				examEditViewModel.Teachers = dbRepository.GetAllTeachers();
				examEditViewModel.ExternalSupervisors = dbRepository.GetAllExternalSupervisors();
				examEditViewModel.ExamTypes = dbRepository.GetAllExamTypes();
				examEditViewModel.ExamGrades = dbRepository.GetAllExamGrades();
			}

			return View(examEditViewModel);
		}

		[HttpPost]
		public ActionResult Edit(ExamEditViewModel exam)
		{
			if (ModelState.IsValid)
			{
				bool newsExam = (exam.ID == 0);

				Exam examEntity = new Exam();
				examEntity.ID = exam.ID;
				examEntity.RegisteredStudent = new RegisteredStudent { ID = exam.RegistredStudentID };
				examEntity.Supervisor = new Teacher { ID = exam.SupervisorID };
				if (exam.ExternalSupervisorID.HasValue && exam.ExternalSupervisorID.Value > 0)
					examEntity.ExternalSupervisor = new ExternalSupervisor { ID = exam.ExternalSupervisorID.Value };
				else
					examEntity.ExternalSupervisor = null;
				examEntity.Grade = new ExamGrade { ID = exam.ExamGradeID };
				examEntity.Type  = new ExamType { ID = exam.ExamTypeID };
				examEntity.Comments = string.IsNullOrWhiteSpace(exam.Comments) ? null : exam.Comments;
				examEntity.BonusPoints = exam.BonusPoints;
				examEntity.Date = exam.Date;

				dbRepository.SaveExam(examEntity);
				TempData["message"] = newsExam ? Messages.ExamAdded : Messages.ExamEditedSuccessfully;

				return RedirectToAction("Edit", "RegisteredStudent", new { id = exam.RegistredStudentID });
			}
			else
			{
				return View(exam);
			}
		}
    }
}

ManarAlSabeel.Web/Views/Exam/Edit.cshtml
@model ManarAlSabeel.Web.Models.ExamEditViewModel
@using ManarAlSabeel.Domain.Entities
@using ManarAlSabeel.Web.Heplers
@using ManarAlSabeel.Web.Models

@{
    ViewBag.Title = "Edit";
}

<h2>@StringTable.EditExamPageTitle</h2>

<div class="panel panel-default" style="width: 45%; margin: 0 auto;">
	<div class="panel-body">

		@using (Html.BeginForm("Edit", "Exam", FormMethod.Post, new { role = "form" }))
		{
			<div class="form-group">
				<label>@StringTable.ExamDate</label>
				@Html.TextBoxFor(x => x.Date,
					new { @class = "form-control date-input", dir = "ltr", Value = Model.Date.ToShortDateString(), data_date_format = "dd/mm/yyyy" })
				@Html.ValidationMessageFor(x => x.Date)
			</div>
			
			<div class="form-group">
				<label>@StringTable.ExamSupervisor</label>
				@Html.DropDownListFor(x => x.SupervisorID,
							@Helpers.TeachersToSelectListItems(Model.Teachers),
					new { @class = "form-control select2" })
				@Html.ValidationMessageFor(x => x.SupervisorID)
			</div>
			
			<div class="form-group">
				<label>@StringTable.ExternalSupervisor</label>
				@Html.DropDownListFor(x => x.ExternalSupervisorID,
					@Helpers.ExternalSupervisorToSelectListItems(Model.ExternalSupervisors, true),
					new { @class = "form-control select2" })
			</div>
			
			<div class="form-group">
				<label>@StringTable.ExamType</label>
				@Html.DropDownListFor(x => x.ExamTypeID,
					@Helpers.ExamTypesToSelectListItems(Model.ExamTypes),
					new { @class = "form-control select2" })
				@Html.ValidationMessageFor(x => x.ExamTypeID)
			</div>
			
			<div class="form-group">
				<label>@StringTable.ExamGrade</label>
				@Html.DropDownListFor(x => x.ExamGradeID,
					@Helpers.ExamGradesToSelectListItems(Model.ExamGrades),
					new { @class = "form-control select2" })
				@Html.ValidationMessageFor(x => x.ExamGradeID)
			</div>
			
			<div class="form-group">
				<label>@StringTable.ExamBonusPoints</label>
				@Html.TextBoxFor(x => x.BonusPoints, new { @class = "form-control" })
			</div>
			
			<div class="form-group">
				<label>@StringTable.ExamComments</label>
				@Html.TextBoxFor(x => x.Comments, new { @class = "form-control" })
				@Html.ValidationMessageFor(x => x.Comments)
			</div>

			@Html.HiddenFor(x => x.ID)
			@Html.HiddenFor(x => x.RegistredStudentID)

			<input type="submit" value="@StringTable.Save"
				   class="btn btn-lg btn-primary btn-block" />
		}
	</div>
</div>

ManarAlSabeel.Web/Views/Exam/List.cshtml
@model ManarAlSabeel.Web.Models.ExamsListViewModel
@using ManarAlSabeel.Domain.Entities

@{
	ViewBag.Title = ManarAlSabeel.Web.Heplers.Helpers.GetPageTitle(@StringTable.ExamsListPageTitle);
}

<h2>@StringTable.ExamsListPageTitle</h2>

<style type="text/css">
	.registered-student-div {
		float: right;
		width: 200px;
		margin: 2px;
	}

	.registered-student-name {
		font-family: Arial;
		font-weight: bold;
		font-size: 13pt;
	}
</style>

<div>
	@foreach (Exam exam in Model.Exams)
	{
		<div class="registered-student-div panel panel-default">
			<div class="panel-body">
				<div>@exam.RegisteredStudent.Student.Name</div>
				<div>@exam.Date.ToShortDateString()</div>
				<div>@exam.Type.Name</div>
				<div>@exam.Grade.Name</div>
			</div>
			<div class="panel-footer">
				<div>
					@Html.ActionLink(StringTable.EditExam, "Edit", new { @exam.ID })
				</div>
			</div>
		</div>
	}
</div>