ManarAlSabeel.Web/Controllers/TeachersController.cs
using ManarAlSabeel.Domain.Abstract;
using ManarAlSabeel.Domain.Entities;
using ManarAlSabeel.Resources;
using ManarAlSabeel.Web.Heplers;
using ManarAlSabeel.Web.Infrastructure;
using ManarAlSabeel.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManarAlSabeel.Web.Controllers
{
	[ForbiddenRedirectAuthorizeAttribute]
    public class TeachersController : Controller
    {
		private ICenterRepository dbRepository;
		private int PageSize = 25;

		public TeachersController(ICenterRepository repo)
		{
			dbRepository = repo;
		}

		public ViewResult List(int page = 1)
		{
			PagingInfo pagingInfo = new PagingInfo
			{
				CurrentPage = page,
				ItemsPerPage = PageSize,
				TotalItems = dbRepository.GetAllTeachers().Count()
			};
			IQueryable<Teacher> teachers = dbRepository.GetAllTeachers().Skip((page - 1) * PageSize)
				.Take(PageSize);

			TeachersListViewModel model = new TeachersListViewModel { Teachers = teachers, PagingInfo = pagingInfo };
			return View(model);
		}

		public ViewResult Edit(int id)
		{
			TeacherEditViewModel teacherViewModel = null;
			Teacher teacherEntity = dbRepository.GetAllTeachers().FirstOrDefault<Teacher>(x => x.ID == id);
			if (teacherEntity != null)
			{
				teacherViewModel = new TeacherEditViewModel();
				teacherViewModel.ID = teacherEntity.ID;
				teacherViewModel.AmountOfMemorization = teacherEntity.AmountOfMemorization;
				teacherViewModel.BirthDate = teacherEntity.BirthDate;

				teacherViewModel.BirthPlaceID = teacherEntity.BirthPlace.ID;
				teacherViewModel.BirthPlaceName = teacherEntity.BirthPlace.Name;
				
				teacherViewModel.BranchID = teacherEntity.Branch.ID;
				teacherViewModel.BranchName = teacherEntity.Branch.Name;

				teacherViewModel.Email = teacherEntity.Email;
				teacherViewModel.HomeNumber = teacherEntity.HomeNumber;
				teacherViewModel.IsSupervisor = teacherEntity.IsSupervisor;
				teacherViewModel.MaritalStatus = teacherEntity.MaritalStatus;
				if (teacherEntity.MarriageDate.HasValue)
					teacherViewModel.MarriageDate = teacherEntity.MarriageDate;
				else
					teacherViewModel.MarriageDate = null;
				teacherViewModel.MobileNumber = teacherEntity.MobileNumber;
				teacherViewModel.Name = teacherEntity.Name;

				teacherViewModel.NationalityID = teacherEntity.Nationality.ID;
				teacherViewModel.NationalityName = teacherEntity.Nationality.Name;

				teacherViewModel.Profession = teacherEntity.Profession;
				teacherViewModel.ReligiousIdeology = teacherEntity.ReligiousIdeology;
				teacherViewModel.Sex = teacherEntity.Sex;
				teacherViewModel.Status = teacherEntity.Status;

				teacherViewModel.Countries = dbRepository.GetAllCountries();
			}

			return View(teacherViewModel);
		}

		[HttpPost]
		public ActionResult Edit(TeacherEditViewModel teacherViewModel)
		{
			if (ModelState.IsValid)
			{
				Teacher teacherEntity = new Teacher();
				//enforce profile values over form values
				teacherEntity.Sex = Helpers.GetProfileSex().Value;
				teacherEntity.Branch = new Branch();
				teacherEntity.Branch.ID = Helpers.GetProfileBranch().ID;

				teacherEntity.ID = teacherViewModel.ID;
				teacherEntity.AmountOfMemorization = teacherViewModel.AmountOfMemorization;
				teacherEntity.BirthDate = teacherViewModel.BirthDate;

				teacherEntity.BirthPlace = new Country();
				teacherEntity.BirthPlace.ID = teacherViewModel.BirthPlaceID;

				teacherEntity.Email = teacherViewModel.Email;
				teacherEntity.HomeNumber = teacherViewModel.HomeNumber;
				teacherEntity.IsSupervisor = teacherViewModel.IsSupervisor;
				teacherEntity.MaritalStatus = teacherViewModel.MaritalStatus;
				teacherEntity.MarriageDate = teacherViewModel.MarriageDate;
				teacherEntity.MobileNumber = teacherViewModel.MobileNumber;
				teacherEntity.Name = teacherViewModel.Name;

				teacherEntity.Nationality = new Country();
				teacherEntity.Nationality.ID = teacherViewModel.NationalityID;

				teacherEntity.Profession = teacherViewModel.Profession;
				teacherEntity.ReligiousIdeology = teacherViewModel.ReligiousIdeology;
				teacherEntity.Status = teacherViewModel.Status;
				
				dbRepository.SaveTeacher(teacherEntity);

				bool newTeacher = (teacherViewModel.ID == 0);
				TempData["message"] = newTeacher ? Messages.TeacherCreatedSuccessfully : Messages.EditTeacherSuccessful;

				return RedirectToAction("List");
			}
			else
			{
				teacherViewModel.Countries = dbRepository.GetAllCountries();
				return View(teacherViewModel);
			}
		}

		public ViewResult Create()
		{
			return View("Edit", new Models.TeacherEditViewModel
			{
				BirthDate = DateTime.Now.Subtract(new TimeSpan(365 * 30, 0, 0, 0)),
				Sex = Helpers.GetProfileSex().Value,
				Countries = dbRepository.GetAllCountries(),
			});
		}

		[HttpPost]
		public ActionResult Delete(int teacherId, string returnUrl)
		{
			bool result = dbRepository.DeleteTeacher(teacherId);
			TempData["message"] = Messages.TeacherDeletedSuccessfully;
			return RedirectToAction("List");
		}
    }
}

ManarAlSabeel.Web/Views/Teachers/Edit.cshtml
@model ManarAlSabeel.Web.Models.TeacherEditViewModel
@using ManarAlSabeel.Domain.Entities
@using ManarAlSabeel.Web.Heplers

@{
	string pageTitle = (Model.ID == 0) ? StringTable.AddTeacher : StringTable.EditTeacherInfo;
	ViewBag.Title = ManarAlSabeel.Web.Heplers.Helpers.GetPageTitle(@StringTable.EditTeacherInfo);
	ManarAlSabeel.Web.Models.BranchViewModel _branch = Helpers.GetBranchViewModel(Model.BranchID, Model.BranchName);
}

<h2>@pageTitle</h2>

<div class="panel panel-default" style="width: 45%; margin: 0 auto;">
	<div class="panel-body">

		@using (Html.BeginForm("Edit", "Teachers", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
		{
			@Html.ValidationSummary(true)

			<div class="form-group">
				<label>@StringTable.Name:</label>
				@Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
				@Html.ValidationMessageFor(x => x.Name)
			</div>

			<div class="form-group">
				<label>@StringTable.DateOfBirth:</label>
				@Html.TextBoxFor(x => x.BirthDate,
					new
					{
						@class = "form-control date-input",
						data_date_format="dd/mm/yyyy",
						Value = Model.BirthDate.ToShortDateString(),
						dir = "ltr"
					})
				@Html.ValidationMessageFor(x => x.BirthDate)
			</div>

			<div class="form-group">
				<label>@StringTable.OriginalNationality</label>
				@Html.DropDownListFor(x => x.NationalityID,
					@ManarAlSabeel.Web.Heplers.Helpers.CountriesToSelectListItems(Model.Countries),
					new { @class = "form-control select2" })
				@Html.ValidationMessageFor(x => x.NationalityID)
			</div>
			
			<div class="form-group">
				<label>@StringTable.Branch</label>
				@Html.TextBox("branch", _branch.Name, new { disabled = "disabled", @class = "form-control" })
				@Html.HiddenFor(x => x.BranchID, new { Value = _branch.ID })
			</div>
			
			<div class="form-group">
				<label>@StringTable.BirthPlace</label>
				@Html.DropDownListFor(x => x.BirthPlaceID,
					@ManarAlSabeel.Web.Heplers.Helpers.CountriesToSelectListItems(Model.Countries),
					new { @class = "form-control select2" })
				@Html.ValidationMessageFor(x => x.BirthPlaceID)
			</div>
			
			<div class="form-group">
				<label>@StringTable.MarriageDate</label>
				@Html.TextBoxFor(x => x.MarriageDate,
					new
					{
						@class = "form-control date-input",
						data_date_format="dd/mm/yyyy",
						Value = Model.MarriageDate.HasValue ?
							Model.MarriageDate.Value.ToShortDateString()
							:
							string.Empty
							,
						dir = "ltr"
					})
				@Html.ValidationMessageFor(x => x.MarriageDate)
			</div>

			<div class="form-group">
				<label>@StringTable.TheProfession</label>
				@Html.TextBoxFor(x => x.Profession, new { Value = Model.Profession, @class = "form-control" })
			</div>
			
			<div class="form-group">
				<label>@StringTable.MobileNumber</label>
				@Html.TextBoxFor(x => x.MobileNumber, new { Value = Model.MobileNumber, @class = "form-control", dir = "ltr" })
				@Html.ValidationMessageFor(x => x.MobileNumber)
			</div>
			
			<div class="form-group">
				<label>@StringTable.HomePhone</label>
				@Html.TextBoxFor(x => x.HomeNumber, new { Value = Model.HomeNumber, @class = "form-control", dir = "ltr" })
			</div>
			
			<div class="form-group">
				<label>@StringTable.Email</label>
				@Html.TextBoxFor(x => x.Email, new { Value = Model.Email, @class = "form-control", dir = "ltr" })
				@Html.ValidationMessageFor(x => x.Email)
			</div>
			
			<div class="form-group">
				<label>@StringTable.QuraanMemorizationAmount</label>
				@Html.TextBoxFor(x => x.AmountOfMemorization, new { Value = Model.AmountOfMemorization,
					@class = "form-control"})
				@Html.ValidationMessageFor(x => x.AmountOfMemorization)
			</div>
			
			<div class="form-group">
				<label>@StringTable.Sex:</label>

				@Html.RadioButtonFor(x => x.Sex, ManarAlSabeel.Domain.Entities.Sex.Male, new { disabled = "disabled" })
				<label>@StringTable.Male</label>
				
				@Html.RadioButtonFor(x => x.Sex, ManarAlSabeel.Domain.Entities.Sex.Female, new { disabled = "disabled" })
				<label>@StringTable.Female</label>
			</div>
			
			<div class="form-group">
				<label>@StringTable.ReligiousIdeology:</label>

				@Html.RadioButtonFor(x => x.ReligiousIdeology, ReligiousIdeology.Hanafy)
				<label>@StringTable.Hanafy</label>
				
				@Html.RadioButtonFor(x => x.ReligiousIdeology, ReligiousIdeology.Hanbaly)
				<label>@StringTable.Hanbally</label>

				@Html.RadioButtonFor(x => x.ReligiousIdeology, ReligiousIdeology.Maleky)
				<label>@StringTable.Malky</label>

				@Html.RadioButtonFor(x => x.ReligiousIdeology, ReligiousIdeology.Shafeey)
				<label>@StringTable.Shafeey</label>
			</div>
			
			<div class="form-group">
				<label>@StringTable.Status:</label>

				@Html.RadioButtonFor(x => x.Status, TeacherStatus.Active)
				<label>@StringTable.Active</label>
				
				@Html.RadioButtonFor(x => x.Status, TeacherStatus.InActive)
				<label>@StringTable.InActive</label>
			</div>
			
			<div class="form-group">
				<label>@StringTable.MaritalStatus:</label>
				@Html.RadioButtonFor(x => x.MaritalStatus, MaritalStatus.Single)
				<label>@StringTable.Single</label>

				@Html.RadioButtonFor(x => x.MaritalStatus, MaritalStatus.Married)
				<label>@StringTable.Married</label>

				@Html.RadioButtonFor(x => x.MaritalStatus, MaritalStatus.Divorced)
				<label>@StringTable.Divorced</label>

				@Html.RadioButtonFor(x => x.MaritalStatus, MaritalStatus.Widow)
				<label>@StringTable.Widow</label>
			</div>
			
			@Html.HiddenFor(x => x.ID)

			<input type="submit" value="@StringTable.Save"
				   class="btn btn-lg btn-primary btn-block" />
		}

	</div>
</div>

ManarAlSabeel.Web/Views/Teachers/List.cshtml
@model ManarAlSabeel.Web.Models.TeachersListViewModel

@{
	ViewBag.Title = ManarAlSabeel.Web.Heplers.Helpers.GetPageTitle(@StringTable.TeachersList);
}

<h2>@StringTable.TeachersList</h2>

<table class="table table-condensed">
	<thead>
		<tr>
			<th>@StringTable.Name</th>
			<th>@StringTable.Age</th>
			<th>@StringTable.Nationality</th>
			<th>@StringTable.MaritalStatus</th>
			<th></th>
		</tr>
	</thead>
	@foreach (ManarAlSabeel.Domain.Entities.Teacher teacher in Model.Teachers)
	{
		<tr>
			<td>
				@Html.ActionLink(teacher.Name, "Edit", new { teacher.ID })
			</td>
			<td>@teacher.Age</td>
			<td>@teacher.Nationality.Name</td>
			<td>@ManarAlSabeel.Web.Heplers.Helpers.GetMaritalStatusCaption(teacher.MaritalStatus)</td>
			<td>
				@using (@Html.BeginForm("Delete", "Teachers"))
				{
					@Html.Hidden("teacherId", teacher.ID)
					@Html.Hidden("returnUrl", "/")
					<input class="btn btn-default btn-xs" type="submit"
						   value="@StringTable.Delete"
						   onclick="return confirm('@StringTable.AreYouSure')" />
				}
			</td>
		</tr>
	}

</table>

<ul class="pagination">
	@Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x }))
</ul>