ManarAlSabeel.Web/Controllers/ClassController.cs
using ManarAlSabeel.Domain.Abstract;
using ManarAlSabeel.Domain.Entities;
using ManarAlSabeel.Resources;
using ManarAlSabeel.Web.Heplers;
using ManarAlSabeel.Web.Infrastructure;
using ManarAlSabeel.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManarAlSabeel.Web.Controllers
{
	[ForbiddenRedirectAuthorizeAttribute]
	public class ClassController : Controller
	{
		private int PageSize = 25;
		private ICenterRepository dbRepository;
		public ClassController(ICenterRepository repo)
		{
			dbRepository = repo;
		}

		public ViewResult List(int page = 1)
		{
			PagingInfo pagingInfo = new PagingInfo
			{
				CurrentPage = page,
				ItemsPerPage = PageSize,
				TotalItems = dbRepository.GetAllClasses().Count()
			};

			IQueryable<Class> classes =
				dbRepository.GetAllClasses().Skip((page - 1) * PageSize).Take(PageSize);
			ClassesListViewModel model = new ClassesListViewModel { Classes = classes, PagingInfo = pagingInfo };

			return View(model);
		}

		public ViewResult Edit(int id)
		{
			ClassEditViewModel viewModel = null;

			Class aClass = dbRepository.GetAllClasses().FirstOrDefault<Class>(x => x.ID == id);
			if(aClass != null)
			{
				viewModel = new ClassEditViewModel();

				viewModel.ClassID = aClass.ID;
				viewModel.ClassName = aClass.Name;
				viewModel.Sex = aClass.Sex;
				viewModel.TeachingPeriod = aClass.TeachingPeriod;
				
				viewModel.TeacherID = aClass.Teacher.ID;
				viewModel.TeacherName = aClass.Teacher.Name;

				viewModel.SemesterID = aClass.Semester.ID;
				viewModel.SemesterName = aClass.Semester.Name;

				viewModel.BranchID = aClass.Branch.ID;
				viewModel.BranchName = aClass.Branch.Name;

				viewModel.Semesters = dbRepository.GetAllSemesters();
				viewModel.Teachers = dbRepository.GetAllTeachers();
			}

			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Edit(ClassEditViewModel aClass)
		{
			if (ModelState.IsValid)
			{
				bool newsClass = (aClass.ClassID == 0);
				
				Class classEntity = new Class();
				classEntity.ID = aClass.ClassID;
				classEntity.Name = aClass.ClassName;
				classEntity.Teacher = new Teacher { ID = aClass.TeacherID };
				classEntity.Semester = new Semester { ID = aClass.SemesterID };
				classEntity.TeachingPeriod = aClass.TeachingPeriod;

				classEntity.Branch = new Branch { ID = Helpers.GetProfileBranch().ID };
				classEntity.Sex = Helpers.GetProfileSex().Value;

				dbRepository.SaveClass(classEntity);
				TempData["message"] = newsClass ? Messages.ClassCreatedSuccessfully : Messages.EditedClassInfoSuccessful;

				return RedirectToAction("List");
			}
			else
			{
				return View(aClass);
			}
		}

		public ViewResult Create()
		{
			return
				View("Edit", new ClassEditViewModel
								{
									Teachers = dbRepository.GetAllTeachers(),
									Semesters = dbRepository.GetAllSemesters(),
									Sex = Helpers.GetProfileSex().Value
								}
					);
		}

		[HttpPost]
		public ActionResult Delete(int classId)
		{
			bool result = dbRepository.DeleteClass(classId);
			TempData["message"] = Messages.ClassDeletedSuccessfully;

			return RedirectToAction("List");
		}
    }
}

ManarAlSabeel.Web/Controllers/SemesterController.cs
using ManarAlSabeel.Domain.Abstract;
using ManarAlSabeel.Domain.Entities;
using ManarAlSabeel.Resources;
using ManarAlSabeel.Web.Heplers;
using ManarAlSabeel.Web.Infrastructure;
using ManarAlSabeel.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManarAlSabeel.Web.Controllers
{
	[ForbiddenRedirectAuthorizeAttribute]
    public class SemesterController : Controller
    {
        private int PageSize = 25;
		private ICenterRepository dbRepository;
		public SemesterController(ICenterRepository repo)
		{
			dbRepository = repo;
		}

		public ViewResult List(int page = 1)
		{
			PagingInfo pagingInfo = new PagingInfo
			{
				CurrentPage = page,
				ItemsPerPage = PageSize,
				TotalItems = dbRepository.GetAllSemesters().Count()
			};
			IQueryable<Semester> semesters = dbRepository.GetAllSemesters().Skip((page - 1) * PageSize).Take(PageSize);
			SemestersListViewModel model = new SemestersListViewModel { Semesters = semesters, PagingInfo = pagingInfo };

			return View(model);
		}

		public ViewResult Edit(int id)
		{
			SemesterEditViewModel semesterViewModel = null;
			Semester semesterEntity = dbRepository.GetAllSemesters().FirstOrDefault<Semester>(x => x.ID == id);
			if(semesterEntity != null)
			{
				semesterViewModel = new SemesterEditViewModel();
				semesterViewModel.ID = semesterEntity.ID;
				semesterViewModel.Name = semesterEntity.Name;
				semesterViewModel.StartDate = semesterEntity.StartDate;
				semesterViewModel.EndDate = semesterEntity.EndDate;
			}

			return View(semesterViewModel);
		}

		[HttpPost]
		public ActionResult Edit(SemesterEditViewModel semesterViewModel)
		{
			if (ModelState.IsValid)
			{
				Semester semesterEntity = new Semester();
				//enforce profile values over form values
				semesterEntity.Branch = new Branch();
				semesterEntity.Branch.ID = Helpers.GetProfileBranch().ID;

				semesterEntity.Name = semesterViewModel.Name;
				semesterEntity.StartDate = semesterViewModel.StartDate;
				semesterEntity.EndDate = semesterViewModel.EndDate;
				semesterEntity.ID = semesterViewModel.ID;

				dbRepository.SaveSemester(semesterEntity);

				bool newsSemester = (semesterViewModel.ID == 0);
				TempData["message"] = newsSemester ? Messages.SemesterCreatedSuccessfully : Messages.EditedSemesterInfoSuccessful;

				return RedirectToAction("List");
			}
			else
			{
				return View(semesterViewModel);
			}
		}

		public ViewResult Create()
		{
			return View("Edit", new SemesterEditViewModel { StartDate = DateTime.Now, EndDate = DateTime.Now.AddDays(6 * 30) });
		}

		[HttpPost]
		public ActionResult Delete(int semesterId)
		{
			bool result = dbRepository.DeleteSemeter(semesterId);
			TempData["message"] = Messages.SemesterDeletedSuccessfully;

			return RedirectToAction("List");
		}
    }
}

ManarAlSabeel.Web/Controllers/StudentController.cs
using ManarAlSabeel.Domain.Abstract;
using ManarAlSabeel.Domain.Entities;
using ManarAlSabeel.Resources;
using ManarAlSabeel.Web.Heplers;
using ManarAlSabeel.Web.Infrastructure;
using ManarAlSabeel.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManarAlSabeel.Web.Controllers
{
	[ForbiddenRedirectAuthorizeAttribute]
    public class StudentController : Controller
    {
		private int PageSize = 25;
		private ICenterRepository dbRepository;
		public StudentController(ICenterRepository repo)
		{
			dbRepository = repo;
		}

		public ViewResult List(int page = 1, int guardianId = 0)
        {
			PagingInfo pagingInfo = new PagingInfo
			{
				CurrentPage = page,
				ItemsPerPage = PageSize,
				TotalItems = (guardianId > 0) ?
					dbRepository.GetAllStudents().Where(x => x.Guardian.ID == guardianId).Count()
					:
					dbRepository.GetAllStudents().Count()
			};
			IQueryable<Student> students;
			students = (guardianId > 0) ?
				dbRepository.GetAllStudents().Where(x => x.Guardian.ID == guardianId).Skip((page - 1) * PageSize).Take(PageSize)
				:
				dbRepository.GetAllStudents().Skip((page - 1) * PageSize).Take(PageSize)
				;

			StudentsListViewModel model = new StudentsListViewModel { Students = students, PagingInfo = pagingInfo };
			return View(model);
        }

		public ViewResult Edit(int id)
		{
			Student studentEntity = dbRepository.GetAllStudents().FirstOrDefault<Student>(x => x.ID == id);
			StudentEditViewModel studentViewModel = null;

			if (studentEntity != null)
			{
				studentViewModel = new StudentEditViewModel();

				studentViewModel.ID = studentEntity.ID;
				studentViewModel.Name = studentEntity.Name;
				studentViewModel.BirthDate = studentEntity.BirthDate;
				studentViewModel.EducationStage = studentEntity.EducationStage;
				studentViewModel.ExpectedQuraanFinishTime = studentEntity.ExpectedQuraanFinishTime;
				studentViewModel.HowKnewTheCenter = studentEntity.HowKnewTheCenter;
				studentViewModel.IsInTransportations = studentEntity.IsInTransportations;
				studentViewModel.LastEducationDegree = studentEntity.LastEducationDegree;
				studentViewModel.PersonalPhotoPath = studentEntity.PersonalPhotoPath;
				studentViewModel.SchoolClass = studentEntity.SchoolClass;
				studentViewModel.SchoolName = studentEntity.SchoolName;
				studentViewModel.Sex = studentEntity.Sex;
				studentViewModel.Status = studentEntity.Status;
				studentViewModel.ProfilePhotoName = studentEntity.ProfilePhotoName;

				studentViewModel.OriginalNationalityID = studentEntity.OriginalNationality.ID;
				studentViewModel.OriginalNationalityName = studentEntity.OriginalNationality.Name;

				if (studentEntity.AcquiredNationality != null && studentEntity.AcquiredNationality.ID != 0)
				{
					studentViewModel.AcquiredNationalityID = studentEntity.AcquiredNationality.ID;
					studentViewModel.AcquiredNationalityName = studentEntity.AcquiredNationality.Name;
				}

				studentViewModel.BranchID = studentEntity.Branch.ID;
				studentViewModel.BranchName = studentEntity.Branch.Name;

				studentViewModel.GuardianID = studentEntity.Guardian.ID;
				studentViewModel.GuardianName = studentEntity.Guardian.Name;

				studentViewModel.Countries = dbRepository.GetAllCountries();
				studentViewModel.Guardians = dbRepository.GetAllStudentGuardians();

				if (studentEntity.AdmissionInterview != null)
				{
					studentViewModel.AdmissionInterviewID = studentEntity.AdmissionInterview.ID;
				}
			}

			return View(studentViewModel);
		}

		[HttpPost]
		public ActionResult Edit(StudentEditViewModel studentViewModel)
		{
			if (ModelState.IsValid)
			{
				bool newsStudent = (studentViewModel.ID == 0);

				Student studentEntity = new Student();
				//enforce profile values over form values
				studentEntity.Sex = Helpers.GetProfileSex().Value;
				studentEntity.Branch = new Branch();
				studentEntity.Branch.ID = Helpers.GetProfileBranch().ID;

				studentEntity.ID = studentViewModel.ID;
				
				studentEntity.AcquiredNationality = new Country();
				studentEntity.AcquiredNationality.ID = studentViewModel.AcquiredNationalityID;

				studentEntity.OriginalNationality = new Country();
				studentEntity.OriginalNationality.ID = studentViewModel.OriginalNationalityID;

				studentEntity.Guardian = new StudentGuardian();
				studentEntity.Guardian.ID = studentViewModel.GuardianID;

				studentEntity.BirthDate = studentViewModel.BirthDate;
				studentEntity.EducationStage = studentViewModel.EducationStage;
				studentEntity.ExpectedQuraanFinishTime = studentViewModel.ExpectedQuraanFinishTime;
				studentEntity.HowKnewTheCenter = studentViewModel.HowKnewTheCenter;
				studentEntity.IsInTransportations = studentViewModel.IsInTransportations;
				studentEntity.LastEducationDegree = studentViewModel.LastEducationDegree;
				studentEntity.Name = studentViewModel.Name;
				studentEntity.PersonalPhotoPath = studentViewModel.PersonalPhotoPath;
				studentEntity.SchoolClass = studentViewModel.SchoolClass;
				studentEntity.SchoolName = studentViewModel.SchoolName;
				studentEntity.Status = studentViewModel.Status;

				if (newsStudent)
					studentEntity.AddedOn = DateTime.Now;

				dbRepository.SaveStudent(studentEntity);

				//save profile photo
				if (Request != null)
				{
					HttpPostedFileBase photoFile = Request.Files["studentPhoto"];
					if(photoFile.ContentLength > 0)
					{
						string fileName = string.Format("student_{0}{1}", studentEntity.ID, Path.GetExtension(photoFile.FileName));
						var savePath = Path.Combine(Server.MapPath(ConfigurationManager.AppSettings["StudentsImagesPath"]),
							fileName);
						photoFile.SaveAs(savePath);

						studentEntity.ProfilePhotoName = fileName;
						dbRepository.SaveStudent(studentEntity);
					}
				}

				TempData["message"] = newsStudent ? Messages.StudentCreatedSuccessfully : Messages.EditStudentSuccessful;

				if (studentViewModel.AddAdmissionInterviewNow)
					return RedirectToAction("Create", "AdmissionInterview", new { studentId = studentEntity.ID });
				else
					return RedirectToAction("List");
			}
			else
			{
				studentViewModel.Countries = dbRepository.GetAllCountries();
				studentViewModel.Guardians = dbRepository.GetAllStudentGuardians();

				return View(studentViewModel);
			}
		}

		public ViewResult Create()
		{
			return View("Edit", new Models.StudentEditViewModel
			{
				BirthDate = DateTime.Now.Subtract(new TimeSpan(365 * 15, 0, 0, 0)),
				Sex = Helpers.GetProfileSex().Value,
				Countries = dbRepository.GetAllCountries(),
				Guardians = dbRepository.GetAllStudentGuardians()
			});
		}

		[HttpPost]
		public ActionResult Delete(int studentId)
		{
			bool result = dbRepository.DeleteStudent(studentId);
			TempData["message"] = Messages.StudentDeletedSuccessfully;

			return RedirectToAction("List");
		}
    }
}

ManarAlSabeel.Web/Views/Shared/HeaderBar.cshtml
@using ManarAlSabeel.Web.Heplers

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			@Html.ActionLink(Helpers.GetBranchCenterHeaderString(), "Index", "Home", null, new { @class = "navbar-brand" })
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-left">

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						@StringTable.PeopleAdministration
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li>
							@Html.ActionLink(@StringTable.StudentList, "List", "Student")
						</li>
						<li>
							@Html.ActionLink(@StringTable.AddStudent, "Create", "Student")
						</li>
						<li role="presentation" class="divider"></li>

						<li>
							@Html.ActionLink(@StringTable.StudentGuardiansList, "List", "StudentGuardian")
						</li>
						<li>
							@Html.ActionLink(@StringTable.AddStudentGuardian, "Create", "StudentGuardian")
						</li>
						<li role="presentation" class="divider"></li>

						<li>
							@Html.ActionLink(@StringTable.TeachersList, "List", "Teachers")
						</li>
						<li>
							@Html.ActionLink(@StringTable.AddTeacher, "Create", "Teachers")
						</li>
					</ul>
				</li>

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						@StringTable.CenterAdministration
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li>
							@Html.ActionLink(@StringTable.SemestersList, "List", "Semester")
						</li>
						<li>
							@Html.ActionLink(@StringTable.AddSemester, "Create", "Semester")
						</li>
						<li role="presentation" class="divider"></li>

						<li>
							@Html.ActionLink(@StringTable.ClassesList, "List", "Class")
						</li>
						<li>
							@Html.ActionLink(@StringTable.AddClass, "Create", "Class")
						</li>
					</ul>
				</li>

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						@User.Identity.Name
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li>
							@Html.ActionLink(@StringTable.Logout, "Logout", "SystemAdmins")
						</li>
					</ul>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div><!--/.nav -container -->
</div>

ManarAlSabeel.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>@ViewBag.Title</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="~/Content/css/bootstrap.rtl.css" rel="stylesheet" media="screen">
	<link href="~/Content/css/bootstrap-datepicker.css" rel="stylesheet" media="screen">

	<link href="~/Content/css/select2.css" rel="stylesheet" media="screen">
	<link href="~/Content/css/select2-bootstrap.css" rel="stylesheet" media="screen">

	<link href="~/Content/css/manar-alsabeel-style.css" type="text/css" rel="stylesheet" />

	<script src="~/Content/js/jquery-1.11.0.min.js"></script>
	<script src="~/Content/js/jquery.validate.min.js"></script>
	<script src="~/Content/js/jquery.validate.unobtrusive.min.js"></script>
	<style>
		body {
			padding-top: 50px;
		}
	</style>
</head>
<body>
	
	@if(@Request.IsAuthenticated)
	{
		Html.RenderPartial("HeaderBar");
	}
	
	@if (TempData["message"] != null)
	{
		<br />
		<div class="alert alert-success" style="width: 45%; margin: 0 auto; text-align:center;">@TempData["message"]</div>
	}

	<div class="container">
		@RenderBody()
	</div>

	<script src="~/Content/js/bootstrap.min.js"></script>
	<script src="~/Content/js/bootstrap-datepicker.js"></script>
	<script src="~/Content/js/select2.min.js"></script>
	<script src="~/Content/js/select2_locale_ar.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			var datePickerObj = $('.date-input');
			datePickerObj.datepicker().on('changeDate', function (ev) {
				datePickerObj.datepicker('hide');
			});

			//select2
			$(".select2").select2({
				placeholder: "Select a State",
				allowClear: true
			});

			//fix chrome date validation
			jQuery.validator.methods.date = function (value, element) {
				var d = value.split("/");
				return this.optional(element) || !/Invalid|NaN/.test(new Date((/chrom(e|ium)/.test(navigator.userAgent.toLowerCase())) ? d[1] + "/" + d[0] + "/" + d[2] : value));
			};
		});
	</script>
</body>
</html>