ManarAlSabeel.Web/Controllers/AdmissionInterviewController.cs
using ManarAlSabeel.Domain.Abstract;
using ManarAlSabeel.Domain.Entities;
using ManarAlSabeel.Resources;
using ManarAlSabeel.Web.Infrastructure;
using ManarAlSabeel.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManarAlSabeel.Web.Controllers
{
	[ForbiddenRedirectAuthorizeAttribute]
    public class AdmissionInterviewController : Controller
    {
		private int PageSize = 25;
		private ICenterRepository dbRepository;
		public AdmissionInterviewController(ICenterRepository repo)
		{
			dbRepository = repo;
		}

		public ViewResult List(int page = 1)
		{
			PagingInfo pagingInfo = new PagingInfo
			{
				CurrentPage = page,
				ItemsPerPage = PageSize,
				TotalItems = dbRepository.GetAllClasses().Count()
			};

			IQueryable<AdmissionInterview> interviews =
				dbRepository.GetAllAdmissionInterviews().Skip((page - 1) * PageSize).Take(PageSize);
			AdmissionInterviewsListViewModel model = new AdmissionInterviewsListViewModel { Interviews = interviews, PagingInfo = pagingInfo };

			return View(model);
		}

		public ViewResult Edit(int id, int studentId)
		{
			AdmissionInterviewEditModel viewModel = null;

			AdmissionInterview interview = dbRepository.GetAllAdmissionInterviews().FirstOrDefault<AdmissionInterview>(x => x.ID == id);
			if (interview != null)
			{
				viewModel = new AdmissionInterviewEditModel();

				viewModel.Date = interview.Date;
				viewModel.MemorizationAmount = interview.MemorizationAmount;
				viewModel.Result = interview.Result;
				viewModel.Notes = interview.Notes;
			}

			viewModel.StudentID = studentId;

			return View(viewModel);
		}

		public ViewResult Create(int studentId)
		{
			return View("Edit", new AdmissionInterviewEditModel { StudentID = studentId, Date = DateTime.Now });
		}

		[HttpPost]
		public ActionResult Edit(AdmissionInterviewEditModel interview)
		{
			if (ModelState.IsValid)
			{
				bool newsClass = (interview.ID == 0);

				AdmissionInterview interviewEntity = new AdmissionInterview();
				interviewEntity.ID = interview.ID;
				interviewEntity.Date = interview.Date;
				interviewEntity.MemorizationAmount = interview.MemorizationAmount;
				interviewEntity.Result = interview.Result;
				interviewEntity.Notes = interview.Notes;

				dbRepository.SaveAddmissionInterview(interviewEntity, interview.StudentID);
				TempData["message"] = newsClass ? Messages.AdmissionInterviewCreated : Messages.AdmissionInterviewUpdated;

				return RedirectToAction("Edit", "Student", new { id = interview.StudentID });
			}
			else
			{
				return View(interview);
			}
		}
    }
}

ManarAlSabeel.Web/Views/AdmissionInterview/Edit.cshtml
@model ManarAlSabeel.Web.Models.AdmissionInterviewEditModel

@using ManarAlSabeel.Domain.Entities
@using ManarAlSabeel.Web.Heplers
@using ManarAlSabeel.Web.Models

@{
	ViewBag.Title = Helpers.GetPageTitle(@StringTable.AdmissionInterviewPage);
}

<h2>@StringTable.AdmissionInterviewPage</h2>

<div class="panel panel-default" style="width: 45%; margin: 0 auto;">
	<div class="panel-body">

		@using (Html.BeginForm("Edit", "AdmissionInterview", FormMethod.Post, new { role = "form" }))
		{
			@Html.ValidationSummary(true)
			
			<div class="form-group">
				<label>@StringTable.AdmissionInterviewDate</label>
				@Html.TextBoxFor(x => x.Date,
								new { @class = "form-control date-input", dir = "ltr", Value = Model.Date.ToShortDateString(), data_date_format = "dd/mm/yyyy" })
				@Html.ValidationMessageFor(x => x.Date)
			</div>
			
			<div class="form-group">
				<label>@StringTable.AdmissionInterviewMemorizationAmount</label>
				@Html.TextBoxFor(x => x.MemorizationAmount, new { @class = "form-control" })
				@Html.ValidationMessageFor(x => x.MemorizationAmount)
			</div>
			
			<div class="form-group">
				<label>@StringTable.AdmissionInterviewResult</label>
				@Html.TextBoxFor(x => x.Result, new { @class = "form-control" })
				@Html.ValidationMessageFor(x => x.Result)
			</div>
			
			<div class="form-group">
				<label>@StringTable.AdmissionInterviewNotes</label>
				@Html.TextBoxFor(x => x.Notes, new { @class = "form-control" })
			</div>
			
			@Html.HiddenFor(x => x.ID)
			@Html.HiddenFor(x => x.StudentID)

			<input type="submit" value="@StringTable.Save"
				   class="btn btn-lg btn-primary btn-block" />
		}
	</div>
</div>

ManarAlSabeel.Web/Views/AdmissionInterview/List.cshtml
@model ManarAlSabeel.Web.Models.AdmissionInterviewsListViewModel
@using ManarAlSabeel.Domain.Entities;

@{
    ViewBag.Title = "List";
}

@foreach (AdmissionInterview interview in Model.Interviews)
{
	<p>@interview.Student.Name</p>
	<p>@interview.Date.ToShortDateString()</p>
	<p>@interview.Committee.FirstOrDefault().InterviewAttendee.Name</p>
}